export const ROUTES: Record<string, string> = {
  HOME: "/",
  ABOUT: "/about",
  CONTACT: "/contact",
  LEARN_MORE: "/learn-more",
  LOGIN: "/login",
  SIGNUP: "/signup",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  SETTINGS: "/settings",
  TASKS: "/tasks",
  WORKSPACE_TASK: "tasks/:workspace",
  TASK: "/:workspace/:task_id",
  DASHBOARD: "/dashboard",
  PROJECTS: "/projects",
  CALENDAR: "/calendar",
  PROFILE: "/profile",
  LOGOUT: "/logout",
  ADMIN_DASHBOARD: "/admin/dashboard",
  MANAGE_USERS: "/admin/users",
  MANAGE_PROJECTS: "/admin/projects",
  REPORTS: "/admin/reports",
  SYSTEM_SETTINGS: "/admin/settings",
  HELP: "/help",
} as const
